# Generated by Django 5.2.6 on 2025-10-02 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournua', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('trophy', models.ImageField(blank=True, null=True, upload_to='trophies/')),
                ('tournament_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=50)),
                ('player_type', models.CharField(choices=[('single', 'Single'), ('team', 'Team')], max_length=50)),
                ('format', models.CharField(choices=[('Knockout', 'Knockout'), ('League', 'League')], max_length=50)),
                ('num_groups', models.IntegerField(default=2)),
                ('teams_per_group', models.IntegerField(default=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournua.tournament')),
            ],
        ),
    ]
