# Generated by Django 5.2.6 on 2025-10-02 16:08


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournua', '0002_tournament_team'),
    ]

    operations = [

        migrations.AlterField(
            model_name='tournament',
            name='teams_per_group',
            field=models.IntegerField(default=4),
        ),
    ]
