# Generated by Django 5.2.7 on 2025-10-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournua', '0003_tournament_code_alter_tournament_teams_per_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='code',
            field=models.CharField(default='TEMP001', editable=False, max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
