# Generated by Django 5.2.7 on 2025-10-07 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournua', '0007_alter_tournament_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='tournua.useraccount'),
            preserve_default=False,
        ),
    ]
