# Generated by Django 5.2.7 on 2025-10-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournua', '0008_alter_tournament_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='joined_tournaments', to='tournua.useraccount'),
        ),
    ]
