# Generated by Django 5.2.6 on 2025-10-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournua', '0009_tournament_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='trophy',
            field=models.CharField(blank=True, choices=[('Trophy1.png', 'Golden Cup'), ('Trophy2.png', 'Silver Cup'), ('Trophy3.png', 'Bronze Cup'), ('Trophy4.png', 'Bronze Cup')], max_length=20, null=True),
        ),
    ]
