# Generated by Django 5.2.7 on 2025-10-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournua', '0010_alter_tournament_trophy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
